# Build settings
markdown: kramdown

gems:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - localstart.bat
  - readme.md

# Custom stuff
title: JSON For mIRC
description: mIRC JSON parser
url: https://sreject.github.io
repository: SReject/JSON-For-Mirc